import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ChevronDown, RefreshCw, Play, Pause, X, SlidersHorizontal } from 'lucide-react';
import Intelligence, { SIMULATION } from './Intelligence.jsx';
import Laboratory from './Laboratory.jsx';
import DiscoveryPanel from './DiscoveryPanel.jsx';
import './discovery.css';
import aporiaMark from '../brand/aporia/assets/logos/symbol-light.svg';
import '@fontsource-variable/manrope';
import '@fontsource-variable/newsreader';
import '@fontsource-variable/newsreader/wght-italic.css';
import './styles.css';
const modeLabels = { idle: 'Idle', exploration: 'Exploration', concentration: 'Concentration', conflict: 'Conflict', insight: 'Insight', collapse: 'Collapse' };
const profileNames = ['explorer', 'formalist', 'skeptic', 'synthesizer', 'minimalist'];
async function api(path, body) { const r = await fetch(`/api/${path}`, body ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : undefined); const data = await r.json(); if (!r.ok) { const error = new Error(data.error || 'The local service could not complete this request.'); error.activeSessionId = data.activeSessionId; throw error; } return data; }
export default function App() {
  const [health, setHealth] = useState(null), [records, setRecords] = useState([]), [session, setSession] = useState(null);
  const [question, setQuestion] = useState(() => (new URLSearchParams(window.location.search).get('question') || '').slice(0, 1400)), [delta, setDelta] = useState(0.6), [model, setModel] = useState(''), [condition, setCondition] = useState('architecture'), [budget, setBudget] = useState(14), [modelMap, setModelMap] = useState({});
  const [view, setView] = useState('research'), [simMode, setSimMode] = useState('idle'), [cycle, setCycle] = useState(false), [motionPaused, setMotionPaused] = useState(false), [selectedProfile, setSelectedProfile] = useState(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [historyOpen, setHistoryOpen] = useState(false), [settingsOpen, setSettingsOpen] = useState(false);
  const events = useRef(null);
  const [workflow, setWorkflow] = useState('discovery'), [targetCount, setTargetCount] = useState(2), [trialBudget, setTrialBudget] = useState(6);
  const [seed, setSeed] = useState(31), [memoryMode, setMemoryMode] = useState('fresh');
  const refresh = async () => { try { const [h, r] = await Promise.all([api('health'), api('sessions')]); setHealth(h); setRecords(r); setModel(current => current || h.models.find(m => m.name === 'qwen2.5:3b')?.name || h.models[0]?.name || ''); } catch { setError('The local engine is unavailable. Restart npm start to reconnect.'); } };
  const connect = id => { events.current?.close(); const e = new EventSource(`/api/sessions/${id}/events`); events.current = e; e.onmessage = message => { const s = JSON.parse(message.data); setSession(s); setError(''); if (!['running', 'paused'].includes(s.status)) { e.close(); refresh(); } }; e.onerror = () => { setError('The research stream disconnected. Your latest record is saved locally; it will reconnect automatically.'); }; };
  useEffect(() => { refresh(); return () => events.current?.close(); }, []);
  useEffect(() => { if (!cycle || view !== 'visual') return; const states = Object.keys(modeLabels); const id = setInterval(() => setSimMode(m => states[(states.indexOf(m) + 1) % states.length]), 6500); return () => clearInterval(id); }, [cycle, view]);
  useEffect(() => { const handler = e => { if (view !== 'visual' || /INPUT|TEXTAREA|SELECT/.test(e.target.tagName) || e.metaKey || e.ctrlKey) return; const mode = Object.keys(modeLabels)[Number(e.key) - 1]; if (mode) { setCycle(false); setSimMode(mode); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [view]);
  const start = async (e, sourceSessionId) => { e?.preventDefault(); setError(''); setBusy(true); try { const s = await api('sessions', { question, delta, condition, model, budget, models: modelMap, seed, memoryMode, workflow: sourceSessionId ? 'discovery' : workflow, targetCount, trialBudget, ...(sourceSessionId ? { sourceSessionId } : {}) }); setSession(s); setWorkflow(s.workflow || 'reflection'); setSelectedProfile(null); connect(s.id); } catch (err) { if (err.activeSessionId) await load(err.activeSessionId); setError(err.message); refresh(); } finally { setBusy(false); } };
  const control = async action => { try { await api(`sessions/${session.id}/control`, { action }); } catch (err) { setError(err.message); } };
  const load = async id => { try { const s = await api(`sessions/${id}`); setSession(s); setQuestion(s.question); setDelta(s.delta); setCondition(s.condition); setModel(s.model); setBudget(s.budget); setSeed(s.seed); setMemoryMode(s.protocol?.memoryMode || 'prior'); setModelMap(Object.fromEntries(s.profiles.map(p => [p.id, p.model]))); setWorkflow(s.workflow || 'reflection'); setTargetCount(s.discovery?.settings.targetCount || 2); setTrialBudget(s.discovery?.settings.trialBudget || 6); setSelectedProfile(null); setHistoryOpen(false); if (['running', 'paused'].includes(s.status)) connect(id); else events.current?.close(); } catch (err) { setError(err.message); } };
  const live = ['running', 'paused'].includes(session?.status);
  const activeRecord = records.find(record => ['running', 'paused'].includes(record.status));
  const otherActive = activeRecord && activeRecord.id !== session?.id;
  const profile = session?.profiles.find(p => p.id === selectedProfile);
  const visual = view === 'visual' ? SIMULATION[simMode] : selectedProfile && profile?.graph.nodes.length ? { ...profile.state, mode: profile.graph.nodes.find(n => n.id === profile.root)?.status === 'rejected' ? 'collapse' : profile.state.contradiction > 0.5 ? 'conflict' : profile.graph.nodes.find(n => n.id === profile.root)?.status === 'surviving' && (profile.quality?.currentHypothesisTests || 0) > 0 && profile.state.confidence > 0.65 && profile.state.uncertainty < 0.35 ? 'insight' : profile.state.uncertainty > 0.55 ? 'exploration' : 'concentration' } : session?.visual || SIMULATION.idle;
  const visualDelta = view === 'visual' ? delta : session?.delta ?? delta;
  const currentMode = modeLabels[visual.mode] || 'Idle';
  return <>
    <header className="site-header"><a href="/" className="wordmark" aria-label="APORIA home"><img src={aporiaMark} width="32" height="32" alt="" /><span>APORIA</span></a><nav aria-label="Laboratory mode"><button aria-current={view === 'research' ? 'page' : undefined} onClick={() => setView('research')}>Research</button><button aria-current={view === 'visual' ? 'page' : undefined} onClick={() => setView('visual')}>Visual studies</button></nav><button className="connection" onClick={refresh} aria-label="Refresh local model connection"><span className={`status-dot ${health?.online ? 'complete' : 'error'}`} />{health ? health.online ? 'Local inference' : 'Inference offline' : 'Connecting'}<RefreshCw size={12} /></button></header>
    <a className="lab-skip" href="#inquiry">Skip to inquiry</a><main><section className={`hero ${session ? 'has-session' : ''}`} aria-label="Cognitive intelligence engine">
      <div className="hero-title"><h1>A space for <em>thought.</em></h1><p>One question. Different ways of thinking.</p></div>
      <div className="sculpture-stage"><div className="stage-note"><span className="tiny-line" /><span>Particle topology<br />{view === 'visual' ? 'State simulation' : session ? 'Research state' : 'Awaiting inquiry'}</span></div><Intelligence state={visual} delta={visualDelta} paused={motionPaused} palette="obsidian" /><div className="stage-readout"><span>{currentMode}</span><span>Δ {visualDelta.toFixed(2)}</span><button onClick={() => setMotionPaused(v => !v)} className="motion-toggle" aria-label={motionPaused ? 'Resume particle animation' : 'Pause particle animation'}>{motionPaused ? <Play size={13} /> : <Pause size={13} />}</button></div></div>
      {view === 'research' ? <div className="inquiry" id="inquiry"><h2>What should we investigate?</h2><form onSubmit={start}><div className="question-input"><input aria-label="Philosophical question" placeholder="Is personal identity dependent on psychological continuity?" value={question} maxLength={1400} onChange={e => setQuestion(e.target.value)} required minLength={12} disabled={live} /><button type="submit" disabled={!health?.online || !model || busy || live || otherActive || question.trim().length < 12}>{busy ? 'Starting' : live ? 'Researching' : 'Start research'}<ArrowRight size={17} /></button></div></form><div className="inquiry-bottom"><p>{workflow === 'discovery' ? 'Published arguments. Tested objections. Ranked research proposals.' : 'Five cognitive policies. Independent trajectories. Shared starting point.'}</p><button className="quiet-button" onClick={() => setSettingsOpen(s => !s)} aria-expanded={settingsOpen}><SlidersHorizontal size={13} /> Experiment setup<ChevronDown size={13} /></button></div>{!question && !session && <div className="example-questions"><span>Begin with</span><button onClick={() => setQuestion('Is personal identity dependent on psychological continuity?')}>Personal identity</button><button onClick={() => setQuestion('Can free will exist in a deterministic universe?')}>Free will</button><button onClick={() => setQuestion('Can a machine have subjective experience?')}>Consciousness</button></div>}</div> : <div className="visual-controls"><div className="simulation-heading"><p>Observe how a thought changes form.</p><span>Simulation · keys 1–6</span></div><div className="mode-buttons">{Object.entries(modeLabels).map(([mode, label], i) => <button key={mode} className={simMode === mode ? 'selected' : ''} aria-pressed={simMode === mode} onClick={() => { setCycle(false); setSimMode(mode); }}><span>{i + 1}</span>{label}</button>)}<button className="cycle-button" aria-pressed={cycle} onClick={() => setCycle(c => !c)}>{cycle ? <Pause size={13} /> : <Play size={13} />} Cycle</button></div><p className="simulation-note">These controls simulate visual states. Switch to Research to observe real controller activity.</p></div>}
      {(settingsOpen && view === 'research') && <div className="experiment-settings"><label>Research workflow<select value={workflow} disabled={live} onChange={e => setWorkflow(e.target.value)}><option value="discovery">Paper-based discovery · complete loop</option><option value="reflection">Cognitive experiment · trajectories</option></select></label>{workflow === 'discovery' && <><label>Papers to investigate<select value={targetCount} disabled={live} onChange={e => setTargetCount(Number(e.target.value))}>{[1, 2, 3, 5].map(n => <option key={n}>{n}</option>)}</select></label><label>Debate trials per paper<select value={trialBudget} disabled={live} onChange={e => setTrialBudget(Number(e.target.value))}>{[1, 3, 6].map(n => <option key={n}>{n}</option>)}</select></label><p className="setup-note">Discovery reads available open-access papers, tests objections, then grades and revises research briefs. Installed local models supply the roles.</p></>}<label>Experimental condition<select value={condition} disabled={live} onChange={e => setCondition(e.target.value)}><option value="architecture">Cognitive architecture</option><option value="baseline">Base model · single pass</option><option value="prompt">Prompt differentiation · shared policy</option><option value="model">Model differentiation · experimental</option></select></label><label>Local model<select value={model} disabled={live} onChange={e => setModel(e.target.value)}>{health?.models.map(m => <option value={m.name} key={m.name}>{m.name} · {m.quantization}</option>)}</select></label><label>Step budget per profile<select value={budget} disabled={live} onChange={e => setBudget(Number(e.target.value))}>{[8, 10, 14, 20, 24].map(n => <option key={n}>{n}</option>)}</select></label><label>Random seed<input type="number" min="0" max="999999" value={seed} disabled={live} onChange={e => setSeed(Math.max(0, Math.min(999999, Math.trunc(Number(e.target.value)))))} /></label><label>Initial memory<select value={memoryMode} disabled={live} onChange={e => setMemoryMode(e.target.value)}><option value="fresh">Fresh state · controlled comparison</option><option value="prior">Learn from prior research</option></select></label><p className="setup-note">A fresh state excludes previous beliefs and learned routing. Prior research preserves that learning. Both modes save the new record.</p>{condition === 'model' && <div className="model-mapping"><p>Choose installed checkpoints to compare. Different families confound architecture and training; quantization alone does not prove cognitive diversity.</p>{profileNames.map(p => <label key={p}>{p}<select value={modelMap[p] || model} disabled={live} onChange={e => setModelMap(m => ({ ...m, [p]: e.target.value }))}>{health?.models.map(m => <option value={m.name} key={m.name}>{m.name}</option>)}</select></label>)}</div>}</div>}
      {otherActive && view === 'research' && <div className="active-session-notice" role="status"><p>A research session is {activeRecord.status === 'paused' ? 'paused' : 'running'}. Open it to resume or stop before starting another.</p><button className="quiet-button" onClick={() => load(activeRecord.id)}>Open active research<ArrowRight size={14} /></button></div>}
      {error && <div className="error-message" role="alert"><p>{error}</p><button onClick={() => setError('')} aria-label="Dismiss error"><X size={15} /></button></div>}
      {health && !health.online && <p className="offline-note">Local inference is offline. Run <code>ollama serve</code> and refresh the connection, or explore Visual studies.</p>}
      <div className="instrument-footer"><div className="delta-control"><label htmlFor="delta">Cognitive differentiation <span>Δ</span></label><input id="delta" type="range" min="0" max="1" step="0.01" value={live && view === 'research' ? session.delta : delta} disabled={live && view === 'research' || condition === 'baseline' && view === 'research'} onChange={e => setDelta(Number(e.target.value))} style={{ '--range': `${(live && view === 'research' ? session.delta : delta) * 100}%` }} /><output htmlFor="delta">{(live && view === 'research' ? session.delta : delta).toFixed(2)}</output></div><div className="memory-label"><span className="memory-mark" />{health?.memory?.memories || 0} local memories<button className="quiet-button" onClick={() => setHistoryOpen(h => !h)} aria-expanded={historyOpen}>Research archive<ChevronDown size={12} /></button></div></div>
      {historyOpen && <div className="archive"><div className="row"><h3>Research archive</h3><button className="icon-button" aria-label="Close archive" onClick={() => setHistoryOpen(false)}><X size={15} /></button></div>{!records.length ? <p className="muted">Your first inquiry will be saved here.</p> : records.map(r => <button key={r.id} onClick={() => load(r.id)}><span>{r.question}</span><small>{new Date(r.created).toLocaleDateString()} · {r.status}</small><ArrowRight size={14} /></button>)}</div>}
    </section>{session && view === 'research' && <>{session.discovery ? <><DiscoveryPanel key={session.id} session={session} onControl={control} /><details className="cognitive-disclosure"><summary>Inspect cognitive trajectories and experiments</summary><Laboratory key={session.id} session={session} onControl={control} onProfile={setSelectedProfile} /></details></> : <><Laboratory key={session.id} session={session} onControl={control} onProfile={setSelectedProfile} />{!live && <div className="cognitive-disclosure develop-directions"><p className="workflow-note">Develop these objections against published papers and assess research proposals.</p><button className="text-button" disabled={busy || otherActive || !health?.online} onClick={() => start(null, session.id)}>Find research directions from this record<ArrowRight size={14} /></button></div>}</>}</>}</main>
    <footer className="page-footer"><span>APORIA · Experimental cognition</span><span>Local inference · literature from OpenAlex. Every conclusion provisional.</span><a href="https://plato.stanford.edu/" target="_blank" rel="noreferrer">Philosophical reference</a></footer>
  </>;
}
