import { useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, Pause, Play, Square } from 'lucide-react';
const labels = { literature: 'Finding relevant papers', fulltext: 'Reading open-access papers', selection: 'Selecting arguments', mapping: 'Reconstructing sourced arguments', indexing: 'Checking the literature', cognition: 'Investigating with cognitive profiles', debate: 'Testing objections', assessment: 'Assessing academic quality', revision: 'Revising research proposals', contribution_novelty: 'Checking final contributions', complete: 'Research finished' };
const num = n => typeof n === 'number' ? n.toFixed(2) : 'Not assessed';
const url = u => /^https?:\/\//i.test(u || '') ? u : undefined;
function Assessment({ a, title = 'Academic assessment' }) {
  return <section className="brief-section"><h4>{title}</h4>{a ? <><p className="brief-grade">{a.grade} · {num(a.overall)} / 5</p><p>{a.summary}</p><dl className="brief-scores">{Object.entries(a.scores).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value} / 5</dd></div>)}</dl><h5>Strongest objection to this proposal</h5><p>{a.strongest_objection}</p><h5>What the paper still needs</h5><p>{a.what_it_needs}</p><details><summary>Reasons for the assessment</summary>{Object.entries(a.reasons || {}).map(([k, v]) => <p key={k}><strong>{k}: </strong>{v}</p>)}</details></> : <p className="muted">Assessment is pending. This proposal has no ranked score yet.</p>}</section>;
}
function Brief({ b, sessionId }) {
  const effective = b.revision?.assessment ? b.revision : b;
  return <article className="research-brief"><div className="row"><h3>{effective.research_question}</h3>{b.markdown && <a className="text-button" href={`/api/sessions/${sessionId}/briefs/${encodeURIComponent(b.id)}`} download><ArrowDownToLine size={14} /> Download brief</a>}</div>
    <p className="muted">From {b.argument.paper_title} · {b.outcome?.replaceAll('_', ' ')}</p>
    <dl className="brief-scores"><div><dt>Lead score</dt><dd>{num(b.score)}</dd></div><div><dt>Final contribution novelty</dt><dd>{num(b.finalNovelty)}</dd></div><div><dt>Academic quality</dt><dd>{num(b.quality == null ? null : b.quality * 5)} / 5</dd></div></dl>
    <p className="metric-note">Lead score = survival × final contribution novelty × quality / 5. Novelty concerns retrieved literature; it does not establish originality.</p>
    {b.rankingReason && <p className="session-warning">{b.rankingReason}. This brief is excluded from ranking.</p>}
    <section className="brief-section"><h4>Paper direction</h4><p>{effective.paper_direction}</p>{effective.reply_to_strongest_objection && <><h5>How the revised paper answers the objection</h5><p>{effective.reply_to_strongest_objection}</p></>}{effective.what_changed && <p className="muted">{effective.what_changed}</p>}</section>
    <Assessment a={effective.assessment} title={effective === b ? 'Academic assessment' : 'Assessment after revision'} />
    <section className="brief-section"><h4>Challenged premise</h4><p>{b.challenged_premise.text}</p><h5>The objection</h5><p>{b.objection}</p><h5>Strongest replies and their limits</h5>{b.strongest_responses.map((r, i) => <div key={i}><h5>{r.defender}</h5><p>{r.response}</p><p className="muted">{r.why_it_failed}</p></div>)}</section>
    <section className="brief-section"><h4>Remaining research questions</h4><ol>{b.open_questions.map((q, i) => <li key={i}>{q}</li>)}</ol></section>
    <section className="brief-section"><h4>Closest literature</h4><p className="muted">{b.contribution_novelty?.records_searched || b.records_searched} indexed records searched. Abstracts and claims are counted separately.</p>{b.closest_literature.map((r, i) => <article className="source-reference" key={`${r.record_id}-${i}`}><p><a href={url(r.url)} target="_blank" rel="noreferrer">{r.title || r.record_id}<ArrowUpRight size={12} /></a> · {r.year} · {r.verdict?.replaceAll('_', ' ')}</p><small>{r.authors?.join(', ')}</small>{r.quote && <blockquote>{r.quote}</blockquote>}<small>{r.scope === 'final_contribution' ? 'Final contribution check' : 'Objection literature'} · similarity {num(r.similarity)}</small></article>)}</section>
    <details className="brief-section"><summary>Published argument and source quotations</summary><ol>{b.argument.premises.map(p => <li key={p.id}><p>{p.text}</p>{p.quote && <blockquote>{p.quote}</blockquote>}<small>{p.id}</small></li>)}</ol>{b.argument.missing_premise && <p>Generated hidden premise: {b.argument.missing_premise.text}</p>}<p><strong>Conclusion: </strong>{b.argument.conclusion.text}</p><p className="muted">Truth-table validity: {b.argument.valid == null ? 'undetermined' : b.argument.valid ? 'valid within the proposed formalization' : 'invalid as stated'}</p></details>
    {b.revision && <details className="brief-section"><summary>Original proposal and assessment</summary><p>{b.paper_direction}</p><Assessment a={b.assessment} />{!b.revision.assessment && <p className="session-warning">The revision could not be assessed. Ranking retains the assessed original.</p>}</details>}
    <p className="metric-note">{b.disclaimer} These are model judgments; a promising score is not acceptance by a journal.</p>
  </article>;
}
export default function DiscoveryPanel({ session: s, onControl }) {
  const d = s.discovery;
  const [tab, setTab] = useState('directions'), [selected, setSelected] = useState(null);
  const list = [...d.briefs].sort((a, b) => (a.rank ?? Infinity) - (b.rank ?? Infinity));
  const b = list.find(x => x.id === selected) || list[0];
  const live = ['running', 'paused'].includes(s.status);
  const trials = d.runs.flatMap(r => r.trials.map(t => ({ ...t, paperTitle: r.target.title })));
  return <section className="laboratory discovery-panel" aria-label="Paper-grounded research discovery"><div className="lab-heading"><div><h2>Where to take your research.</h2><p>{s.question}</p></div><div className="lab-actions">{live && <><button className="icon-button" aria-label={s.status === 'paused' ? 'Resume research' : 'Pause research'} onClick={() => onControl(s.status === 'paused' ? 'resume' : 'pause')}>{s.status === 'paused' ? <Play size={16} /> : <Pause size={16} />}</button><button className="icon-button" aria-label="Stop research" onClick={() => onControl('stop')}><Square size={14} /></button></>}<a className="text-button" href={`/api/sessions/${s.id}/export`} download><ArrowDownToLine size={14} /> Export research</a></div></div>
    <div className="run-meta"><span>{s.status === 'paused' ? 'Paused' : labels[d.stage] || d.stage} · {s.status}</span><span>{d.corpus?.distinctWorks || 0} works · {d.corpus?.fulltexts || 0} full texts · {trials.length} trials · {list.length} briefs</span></div>
    {live && <><div className="run-progress" role="progressbar" aria-label="Discovery progress" aria-valuenow={Math.round(d.progress * 100)} aria-valuemin={0} aria-valuemax={100}><div style={{ transform: `scaleX(${d.progress})` }} /></div><p className="discovery-activity" aria-live="polite">{d.detail}{d.activeRole && <span className="muted"> · {d.activeRole}</span>}</p></>}
    {s.error && <p className="session-warning" role="alert">{s.error}. The partial record and any retrieved papers are preserved.</p>}
    {d.models && !d.models.diversity?.independentFamilies && <p className="session-warning">Only one model family is installed. Roles are separated, but their judgments are not independent family comparisons.</p>}
    <div className="view-tabs" role="group" aria-label="Discovery views">{['directions', 'papers', 'debates', 'research log'].map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{t[0].toUpperCase() + t.slice(1)}</button>)}</div>
    {tab === 'directions' && (b ? <div className="directions-layout"><ol className="direction-list">{list.map(x => { const latest = x.revision?.assessment ? x.revision : x; return <li key={x.id}><button aria-pressed={b.id === x.id} onClick={() => setSelected(x.id)}><span className="direction-rank">{x.rank ? `#${x.rank}` : x.rankingReason ? 'Unranked' : live ? 'Pending' : 'Unranked'}</span><span>{latest.research_question}<small>{x.grade || 'Not assessed'} · lead {num(x.score)}</small></span></button></li>; })}</ol><Brief b={b} sessionId={s.id} /></div> : <div className="discovery-empty"><h3>{live ? 'Building a research brief takes evidence.' : 'No research direction was produced.'}</h3><p>{live ? 'The lab retrieves papers, reconstructs arguments, tests objections, then assesses and revises the strongest directions. Papers and debates appear as they are ready.' : 'Inspect the papers, debate outcomes and recorded failures to see what was ruled out or could not be assessed.'}</p></div>)}
    {tab === 'papers' && <div className="discovery-papers"><p className="muted">{d.corpus?.queries?.join(' · ') || 'Literature search is being prepared.'}</p>{d.targets.map(t => <p key={t.id}><strong>Selected: {t.title}</strong> · {t.reason}</p>)}{d.papers.map(p => <details key={p.id} className="source-reference"><summary>{p.title} · {p.year} · {p.pdf_path ? 'full text' : 'abstract only'}</summary><p>{p.authors.join(', ')} · {p.venue}</p><p>{p.abstract}</p><div className="lab-actions"><a className="text-button" href={url(p.url)} target="_blank" rel="noreferrer">Open paper<ArrowUpRight size={14} /></a>{p.pdf_path && <a className="text-button" href={`/api/sessions/${s.id}/paper?id=${encodeURIComponent(p.id)}`} target="_blank" rel="noreferrer">Read cached source text<ArrowUpRight size={14} /></a>}</div>{p.sourceDigest && <small>Source SHA-256: {p.sourceDigest}</small>}</details>)}{!d.papers.length && <p className="empty">Retrieved papers will appear here.</p>}</div>}
    {tab === 'debates' && <div className="discovery-debates">{d.runs.map(r => <section key={r.run_id}><h3>{r.target.title}</h3>{r.trials.map(t => { const o = r.objections.find(o => o.id === t.objection_id); return <details key={t.id} className="source-reference"><summary>{t.status === 'failed' ? 'Failed trial' : t.outcome?.replaceAll('_', ' ')} · {o?.target_premise_id}</summary><h4>Objection</h4><p>{o?.text}</p><p className="muted">{o?.agent} · {o?.family} · objection novelty {num(r.novelty[o?.id]?.novelty)}</p><p>{t.rationale || t.error}</p>{t.deciding_quote && <blockquote>{t.deciding_quote}</blockquote>}{t.rounds.map((turn, i) => <article className="debate-turn" key={i}><h5>{turn.speaker.replaceAll('_', ' ')} · {turn.phase} · {turn.family}</h5><p>{turn.content}</p>{turn.cited_claim_ids?.length > 0 && <small>Verified citation IDs: {turn.cited_claim_ids.join(', ')}</small>}{turn.struck_claim_ids?.length > 0 && <p className="session-warning">Struck citations: {turn.struck_claim_ids.join(', ')}</p>}</article>)}</details>; })}</section>)}{!trials.length && <><p className="empty">{d.stage === 'debate' ? 'The first trial is running. Live turns are listed below.' : 'Debates will appear after arguments and objections are prepared.'}</p>{d.events.filter(e => e.type === 'turn').slice(-6).map((e, i) => <article className="debate-turn" key={i}><h5>{e.turn.speaker} · {e.turn.phase}</h5><p>{e.turn.content}</p></article>)}</>}</div>}
    {tab === 'research log' && <div className="discovery-log"><p>{d.usage?.calls || 0} literature/debate model calls · {(d.usage?.outputTokens || 0).toLocaleString()} generated tokens. Cognitive compute is recorded in the trajectories below.</p>{d.bridge && <p>{d.bridge.mappedObjections} objections from the stateful reasoners entered the paper-based lab.</p>}{d.failures.map((f, i) => <p className="session-warning" key={i}>{f.stage}: {f.error}</p>)}<ol>{d.events.filter(e => ['stage', 'model_call', 'run_start', 'trial_end', 'brief', 'failure', 'run_end'].includes(e.type)).slice(-100).map((e, i) => <li key={i}><time>{new Date(e.time * 1000).toLocaleTimeString()}</time><span>{e.detail || e.role || e.note || `${e.type} ${e.outcome || ''}`}</span></li>)}</ol></div>}
  </section>;
}
