import { useState } from 'react';
import { ArrowDownToLine, Pause, Play, Square, ArrowUpRight } from 'lucide-react';
import ArgumentGraph from './ArgumentGraph.jsx';
import ResearchDossier from './ResearchDossier.jsx';
const names = { explorer: 'Explorer', formalist: 'Formalist', skeptic: 'Skeptic', synthesizer: 'Synthesizer', minimalist: 'Minimalist' };
const percent = x => x === null || x === undefined ? '—' : `${Math.round(x * 100)}%`;
const policyValue = value => typeof value === 'number' ? value.toFixed(Number.isInteger(value) ? 0 : 2) : typeof value === 'boolean' ? value ? 'enabled' : 'disabled' : String(value);
function ConfidencePlot({ profile }) {
  const data = profile.history.filter(h => h.after?.confidence !== undefined);
  if (!data.length) return null;
  const points = data.map((h, i) => `${12 + i * (316 / Math.max(1, data.length - 1))},${80 - h.after.confidence * 64}`).join(' ');
  const uncertainty = data.map((h, i) => `${12 + i * (316 / Math.max(1, data.length - 1))},${80 - h.after.uncertainty * 64}`).join(' ');
  return <div className="confidence-plot"><svg viewBox="0 0 340 96" role="img" aria-label="Confidence and uncertainty over reasoning steps"><path d="M12 16H328 M12 48H328 M12 80H328" stroke="#24303b" strokeWidth=".5" /><polyline points={points} fill="none" stroke="#90c7db" strokeWidth="1.4" /><polyline points={uncertainty} fill="none" stroke="#b5a4d4" strokeWidth="1.2" strokeDasharray="3 3" /><text x="12" y="94" fill="#8d9aa9" fontSize="8">FIRST STEP</text><text x="287" y="94" fill="#8d9aa9" fontSize="8">LATEST</text></svg><div className="plot-legend"><span>Confidence {percent(profile.state.confidence)}</span><span>Uncertainty {percent(profile.state.uncertainty)}</span></div></div>;
}
export default function Laboratory({ session, onControl, onProfile }) {
  const [selected, setSelected] = useState(session.profiles[0].id);
  const [view, setView] = useState('argument');
  const p = session.profiles.find(p => p.id === selected) || session.profiles[0];
  const active = ['running', 'paused'].includes(session.status);
  const m = session.metrics;
  const position = p.error || p.position || p.graph.nodes.find(n => n.id === p.root)?.text || 'Waiting for the initial hypothesis.';
  const firstSentence = position.match(/^.*?[.!?](?:\s|$)/)?.[0]?.trim() || position;
  const preview = firstSentence.length > 240 ? `${firstSentence.slice(0, 237).trim()}…` : firstSentence;
  return <section className="laboratory" id="laboratory" aria-label="Research laboratory">
    <div className="lab-heading"><div><h2>Thought, made observable.</h2><p>{session.question}</p></div><div className="lab-actions">{active && <><button className="icon-button" onClick={() => onControl(session.status === 'paused' ? 'resume' : 'pause')} aria-label={session.status === 'paused' ? 'Resume research' : 'Pause research'}>{session.status === 'paused' ? <Play size={16} /> : <Pause size={16} />}</button><button className="icon-button" onClick={() => onControl('stop')} aria-label="Stop research"><Square size={14} /></button></>}<a className="text-button" href={`/api/sessions/${session.id}/export`} download><ArrowDownToLine size={15} /> Export record</a></div></div>
    {session.error && <p className="session-warning" role="status">{session.error}</p>}<div className="run-meta"><span>{session.status === 'running' ? `Investigating · ${names[session.activeProfile] || 'initializing'} / ${session.activeOperation || 'starting'}` : session.status.replaceAll('_', ' ')}</span><span>Δ {session.delta.toFixed(2)} · {session.condition} · seed {session.seed} · {session.budget} steps / profile</span></div>
    <div className="run-progress" role="progressbar" aria-label="Research progress" aria-valuenow={Math.round(session.progress * 100)} aria-valuemin={0} aria-valuemax={100}><div style={{ transform: `scaleX(${session.progress})` }} /></div>
    <div className="profile-tabs" role="group" aria-label="Cognitive profiles">{session.profiles.map(profile => <button aria-pressed={p.id === profile.id} key={profile.id} className={p.id === profile.id ? 'selected' : ''} onClick={() => { setSelected(profile.id); onProfile(profile.id); }}><span className={`status-dot ${profile.status}`} />{names[profile.id]}<span className="tab-step">{profile.history.length}/{session.budget}</span></button>)}</div>
    <div className="lab-body"><aside className="profile-summary"><h3>{names[p.id]}</h3><p className="model-name">{p.model}</p><p className="position">{preview}</p>{position !== preview && <details key={`${p.id}:${position}`} className="position-detail"><summary>{p.error ? 'Failure details' : p.position ? 'Full provisional position' : 'Full initial hypothesis'}</summary><p>{position}</p></details>}{p.position && <span className="stance">{p.stance} · provisional</span>}<ConfidencePlot profile={p} />{p.nextQuestion && <div className="next-question"><h4>Next question</h4><p>{p.nextQuestion}</p></div>}
      <details><summary>Computational policy</summary><dl>{Object.entries(p.policy).filter(([k]) => !['weights', 'tools'].includes(k)).map(([k, v]) => <div key={k}><dt>{k.replace(/([A-Z])/g, ' $1').toLowerCase()}</dt><dd>{policyValue(v)}</dd></div>)}</dl><div className="allocation">{Object.entries(p.policy.weights).map(([op, weight]) => <div key={op}><span>{op}</span><div><i style={{ width: `${weight / 2.5 * 100}%` }} /></div><b>{weight.toFixed(2)}</b></div>)}</div><p className="muted">Logic {p.policy.tools.logic ? 'enabled' : 'disabled'} · reading index {p.policy.tools.readings ? 'enabled' : 'disabled'}</p></details>
    </aside><div className="research-inspector"><div className="view-tabs" role="group" aria-label="Research views">{['argument', 'trajectory', 'experiments', 'memory', 'dossier'].map(v => <button key={v} aria-pressed={view === v} onClick={() => setView(v)}>{v === 'argument' ? 'Argument model' : v === 'dossier' ? 'Research dossier' : v[0].toUpperCase() + v.slice(1)}</button>)}</div>
      {view === 'dossier' && <ResearchDossier session={session} profile={p} />}
      {view === 'argument' && <ArgumentGraph profile={p} />}
      {view === 'trajectory' && <div className="trajectory">{!p.history.length && <p className="empty muted">Controller decisions will appear here.</p>}{p.history.map((h, i) => <details key={i} className="history-item" open={i === p.history.length - 1}><summary><span className="step">{String(h.step).padStart(2, '0')}</span><span>{h.operation}</span><span className="gain">{h.error ? 'failed' : `gain ${(h.informationGain || 0).toFixed(2)}`}</span></summary><p>{h.detail}</p><p className="routing-reason">{h.reason}</p>{!h.error && <div className="audit-values"><span>Confidence {percent(h.before?.confidence)} → {percent(h.after?.confidence)}</span><span>Utility {(h.utilityBefore || 0).toFixed(2)} → {(h.utilityAfter || 0).toFixed(2)}</span><span>{h.usage?.cached ? 'Identical proposal reused' : `${h.usage?.output || 0} generated tokens`}</span></div>}{h.tool && <pre>{JSON.stringify(h.tool, null, 2)}</pre>}</details>)}</div>}
      {view === 'experiments' && <div className="experiments">{!p.experiments.length && <p className="empty muted">Counterfactual worlds become experiments after adversarial testing.</p>}{p.experiments.map(e => <article key={e.id}><div className="row"><h4>Counterfactual {e.id.slice(1)}</h4><span className={`verdict ${e.verdict}`}>{e.verdict}</span></div><p>{e.scenario}</p><dl><div><dt>Prediction</dt><dd>{e.prediction}</dd></div><div><dt>Assessment</dt><dd>{e.result}</dd></div></dl><small>{e.limitation}</small></article>)}</div>}
      {view === 'memory' && <div className="memory-view"><p className="muted">{session.protocol?.memoryMode === 'fresh' ? 'Fresh-state control: no earlier beliefs or learned routing entered this run.' : `Prior-state snapshot: ${p.policy.memoryScope || 'shared'} retrieval scope. Retrieved objections retain their original status.`}</p>{!p.memoryHits.length && <p className="empty">No relevant prior memories retrieved.</p>}{p.memoryHits.map(m => <article key={m.id}><div className="row"><span>{m.type} · {m.status}</span><span>{Math.round(m.similarity * 100)}% token match</span></div><p>{m.text}</p><small>Previous research: {m.question}</small></article>)}{p.readings.length > 0 && <><h4>Reading pointers</h4><p className="muted">Curated bibliography. These links do not supply evidence to the model.</p>{p.readings.map(r => <a href={r.url} target="_blank" rel="noreferrer" key={r.url} className="reading-link">{r.title}<ArrowUpRight size={14} /></a>)}</>}</div>}
    </div></div>
    <div className="comparison"><div className="row"><h3>Different paths, measured.</h3><span>{m.profilesCompared} of {m.totalProfiles ?? session.profiles.length} completed positions · {m.failedProfiles ?? session.profiles.filter(p => p.status === 'error').length} failed</span></div><div className="metrics-table"><dl>{[[m.similarityBasis ? 'Semantic argument diversity' : 'Lexical argument diversity', m.argumentDiversity], ['Branch diversity', m.branchDiversity], ['Path similarity', m.pathSimilarity], ['Conclusion similarity', m.conclusionSimilarity], ['Stance disagreement', m.disagreementRate]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{percent(value)}</dd></div>)}</dl></div><div className="metric-counts"><span>{m.uniqueHypotheses} unique hypotheses</span><span>{m.uniqueAssumptions} assumptions</span><span>{m.uniqueObjections} objections</span><span>{m.rejectedHypotheses} rejected hypotheses</span><span>{m.tokens.toLocaleString()} generated tokens</span></div><p className="metric-note">{m.limitation} Confidence and information gain are controller heuristics. {session.metricWarning}</p><details><summary>Compare positions & compute allocation</summary><div className="comparison-scroll"><table><thead><tr><th>Profile</th><th>Position</th><th>Operation path</th><th>Compute by function</th></tr></thead><tbody>{session.profiles.map(p => <tr key={p.id}><td>{names[p.id]}<small>{p.model}</small></td><td>{p.position || 'Awaiting synthesis'}<small>{p.stopReason || p.error}</small></td><td>{p.history.map(h => h.operation).join(' → ')}</td><td>{Object.entries(p.history.reduce((a, h) => ({ ...a, [h.operation]: (a[h.operation] || 0) + (h.usage?.output || 0) }), {})).map(([k, n]) => `${k}: ${n} tokens`).join(' · ')}</td></tr>)}</tbody></table></div></details></div>
  </section>;
}
